// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg1LOr7fQW-xwYll9YZGNzKUM8ie1JL6k',
    appId: '1:639178484796:web:4e1e919bdb2c028abba739',
    messagingSenderId: '639178484796',
    projectId: 'medezz-38ea0',
    authDomain: 'medezz-38ea0.firebaseapp.com',
    storageBucket: 'medezz-38ea0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzOrKUyEB6UTvM-2IkDDFnvBVBTl29pE',
    appId: '1:639178484796:android:8cca83977002345ebba739',
    messagingSenderId: '639178484796',
    projectId: 'medezz-38ea0',
    storageBucket: 'medezz-38ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3o4Cmxh9zFfdsvjuxNkwrIlUARTTiww',
    appId: '1:639178484796:ios:beb33efabc120f5ebba739',
    messagingSenderId: '639178484796',
    projectId: 'medezz-38ea0',
    storageBucket: 'medezz-38ea0.appspot.com',
    iosBundleId: 'com.example.medezz',
  );
}
