name: medezz
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_local_notifications: 
  font_awesome_flutter: ^10.5.0
  iconsax: ^0.0.8
  flutter_styled_toast: ^2.2.1
  flutter_markdown: any
  
  # API and STORAGE
  http: any
  shared_preferences: ^2.2.0
  flutter_gemini: ^2.0.3
  google_generative_ai: any

  # ZEGO
  zego_uikit_prebuilt_call: ^3.18.0
  zego_uikit_signaling_plugin: ^2.7.1
  zego_uikit: ^2.15.1
  
  # FIREBASE
  firebase_core: ^2.25.4
  firebase_storage: ^11.5.6
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  intl: ^0.18.1
  web_socket_channel: ^2.4.4
  health: ^9.0.1
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/icon_small.png
    - assets/icon.png
    - assets/user.png
    - assets/images/doctors/